apiVersion: v1
kind: Pod
metadata:
  name: builder
  serviceAccountName: builder
spec:
  containers:
  - name: kubectl
    image: joshendriks/alpine-k8s
    command:
    - /bin/cat
    tty: true
    resources: {}
  - name: kaniko
    image: gcr.io/kaniko-project/executor:debug
    command:
    - /busybox/cat
    tty: true
    volumeMounts:
      - name: kaniko-secret
        mountPath: /kaniko/.docker
    resources: {}
  volumes:
  - name: kaniko-secret
    secret:
      secretName: docker-credentials 
      items:
        - key: .dockerconfigjson
          path: config.json

  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
