apiVersion: v1
kind: Pod
metadata:
  name: jenkins
spec:
  serviceAccountName: jenkins
  containers:
  - name: kubectl
    image: joshendriks/alpine-k8s
    command:
    - /bin/cat
    tty: true
    resources: {}
  - name: kaniko
    image: gcr.io/kaniko-project/executor:debug
    command:
      # - sh
      # - "-c"
      # - "echo '192.168.2.106 harbor.local' >> /etc/hosts && sleep 3600"
    - /busybox/cat
    tty: true
    volumeMounts:
      - name: kaniko-secret
        mountPath: /kaniko/.docker
      - name: etc-hosts
        mountPath: /etc/hosts
    resources: {}
  volumes:
  - name: kaniko-secret
    secret:
      secretName: harbor-registry-secret
      items:
        - key: .dockerconfigjson
          path: config.json
  - name: etc-hosts
    hostPath:
      path: /etc/hosts
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
