apiVersion: v1
kind: Pod
metadata:
  name: jenkins
spec:
  serviceAccountName: jenkins
  containers:
  - name: kubectl
    image: joshendriks/alpine-k8s
    command:
    - /bin/cat
    tty: true
    resources: {}
  - name: kaniko
    image: gcr.io/kaniko-project/executor:debug
    args:
      - "sh"
      - "-c"
      - "echo '192.168.2.106 harbor.local' >> /etc/hosts && /busybox/cat"
    tty: true
    volumeMounts:
      - name: kaniko-secret
        mountPath: /kaniko/.docker
    resources: {}
  volumes:
  - name: kaniko-secret
    secret:
      secretName: harbor-registry-secret
      items:
        - key: .dockerconfigjson
          path: config.json
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
