apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: simple-app
  name: simple-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-app
  strategy: {}
  template:
    metadata:
      labels:
        app: simple-app
    spec:
      containers:
      - image: dinhhuy1997/simple-app:v1
        name: simple-app
        resources: {}
status: {}
