apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: simple-app
  name: simple-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-app
  strategy: {}
  template:
    metadata:
      labels:
        app: simple-app
        update: "1705856861"
    spec:
      containers:
      - image: harbor.local:30003/webapp/hello-kaniko:latest
        imagePullPolicy: Always
        imagePullSecrets:
        - name: harbor-registry-secret
        name: simple-app
        resources: {}
status: {}
